// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// criterion_cpp
double criterion_cpp(int pp, IntegerVector idx, NumericVector w, int info_mode, const arma::mat& info_data, const arma::mat& wb, const arma::mat& infor0);
RcppExport SEXP _owea_criterion_cpp(SEXP ppSEXP, SEXP idxSEXP, SEXP wSEXP, SEXP info_modeSEXP, SEXP info_dataSEXP, SEXP wbSEXP, SEXP infor0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type info_mode(info_modeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type info_data(info_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wb(wbSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type infor0(infor0SEXP);
    rcpp_result_gen = Rcpp::wrap(criterion_cpp(pp, idx, w, info_mode, info_data, wb, infor0));
    return rcpp_result_gen;
END_RCPP
}
// verify_equiv_cpp
List verify_equiv_cpp(int pp, const arma::mat& wb, int info_mode, const arma::mat& info_data, const arma::mat& opt_infor, const arma::mat& infor0);
RcppExport SEXP _owea_verify_equiv_cpp(SEXP ppSEXP, SEXP wbSEXP, SEXP info_modeSEXP, SEXP info_dataSEXP, SEXP opt_inforSEXP, SEXP infor0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wb(wbSEXP);
    Rcpp::traits::input_parameter< int >::type info_mode(info_modeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type info_data(info_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type opt_infor(opt_inforSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type infor0(infor0SEXP);
    rcpp_result_gen = Rcpp::wrap(verify_equiv_cpp(pp, wb, info_mode, info_data, opt_infor, infor0));
    return rcpp_result_gen;
END_RCPP
}
// directional_deriv_cpp
arma::vec directional_deriv_cpp(int pp, const arma::mat& wb, int info_mode, const arma::mat& info_data, const arma::mat& opt_infor, const arma::mat& infor0);
RcppExport SEXP _owea_directional_deriv_cpp(SEXP ppSEXP, SEXP wbSEXP, SEXP info_modeSEXP, SEXP info_dataSEXP, SEXP opt_inforSEXP, SEXP infor0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wb(wbSEXP);
    Rcpp::traits::input_parameter< int >::type info_mode(info_modeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type info_data(info_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type opt_infor(opt_inforSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type infor0(infor0SEXP);
    rcpp_result_gen = Rcpp::wrap(directional_deriv_cpp(pp, wb, info_mode, info_data, opt_infor, infor0));
    return rcpp_result_gen;
END_RCPP
}
// optimize_weights_cpp
List optimize_weights_cpp(int pp, const arma::mat& wb, int info_mode, const arma::mat& info_data, const arma::mat& infor0, int min_support);
RcppExport SEXP _owea_optimize_weights_cpp(SEXP ppSEXP, SEXP wbSEXP, SEXP info_modeSEXP, SEXP info_dataSEXP, SEXP infor0SEXP, SEXP min_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wb(wbSEXP);
    Rcpp::traits::input_parameter< int >::type info_mode(info_modeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type info_data(info_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type infor0(infor0SEXP);
    Rcpp::traits::input_parameter< int >::type min_support(min_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_weights_cpp(pp, wb, info_mode, info_data, infor0, min_support));
    return rcpp_result_gen;
END_RCPP
}
// appro_opt_cpp
List appro_opt_cpp(int pp, const arma::mat& wb, int info_mode, const arma::mat& info_data, const arma::mat& infor0, IntegerVector init_idx, int min_support, int max_iter, double tol, bool verbose);
RcppExport SEXP _owea_appro_opt_cpp(SEXP ppSEXP, SEXP wbSEXP, SEXP info_modeSEXP, SEXP info_dataSEXP, SEXP infor0SEXP, SEXP init_idxSEXP, SEXP min_supportSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wb(wbSEXP);
    Rcpp::traits::input_parameter< int >::type info_mode(info_modeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type info_data(info_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type infor0(infor0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type init_idx(init_idxSEXP);
    Rcpp::traits::input_parameter< int >::type min_support(min_supportSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(appro_opt_cpp(pp, wb, info_mode, info_data, infor0, init_idx, min_support, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_owea_criterion_cpp", (DL_FUNC) &_owea_criterion_cpp, 7},
    {"_owea_verify_equiv_cpp", (DL_FUNC) &_owea_verify_equiv_cpp, 6},
    {"_owea_directional_deriv_cpp", (DL_FUNC) &_owea_directional_deriv_cpp, 6},
    {"_owea_optimize_weights_cpp", (DL_FUNC) &_owea_optimize_weights_cpp, 6},
    {"_owea_appro_opt_cpp", (DL_FUNC) &_owea_appro_opt_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_owea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
