# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

criterion_cpp <- function(pp, idx, w, info_mode, info_data, wb, infor0) {
    .Call(`_owea_criterion_cpp`, pp, idx, w, info_mode, info_data, wb, infor0)
}

verify_equiv_cpp <- function(pp, wb, info_mode, info_data, opt_infor, infor0) {
    .Call(`_owea_verify_equiv_cpp`, pp, wb, info_mode, info_data, opt_infor, infor0)
}

directional_deriv_cpp <- function(pp, wb, info_mode, info_data, opt_infor, infor0) {
    .Call(`_owea_directional_deriv_cpp`, pp, wb, info_mode, info_data, opt_infor, infor0)
}

optimize_weights_cpp <- function(pp, wb, info_mode, info_data, infor0, min_support) {
    .Call(`_owea_optimize_weights_cpp`, pp, wb, info_mode, info_data, infor0, min_support)
}

appro_opt_cpp <- function(pp, wb, info_mode, info_data, infor0, init_idx, min_support, max_iter, tol, verbose) {
    .Call(`_owea_appro_opt_cpp`, pp, wb, info_mode, info_data, infor0, init_idx, min_support, max_iter, tol, verbose)
}

